name: Upload Binaries
on: [push, pull_request]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        shell: bash
        run: |
          cmake -E make_directory $GITHUB_WORKSPACE/build
          cmake -B $GITHUB_WORKSPACE/build -S $GITHUB_WORKSPACE \
             -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        shell: bash
        run: |
          cmake --build $GITHUB_WORKSPACE/build -j4 --target install
          ls $GITHUB_WORKSPACE/install
          mkdir bins
          mv $GITHUB_WORKSPACE/install/** bins/
      - name: Upload the ecat xml
        uses: actions/upload-artifact@v2
        with:
          name: bins_${{ github.sha }}
          path:  bins